[package]
name = "common"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

[dependencies]
ansi_term = "*"
nom = "*"
error-chain = "*"
term = { path = "../term" }
system = { path = "../system" }
